# Generated by Django 2.1.2 on 2018-10-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_form_section_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='order_sort',
            field=models.IntegerField(default=1, verbose_name='Number page'),
        ),
    ]
